services:
  domain.authentication:
    class: WebDiario\CoreBundle\Services\Authentication\AuthenticationService
    calls:
      - [ setEntityManager, [@doctrine.orm.entity_manager]]
      - [ setContainer, [@service_container]]

  domain.students:
    class: WebDiario\CoreBundle\Services\Students\StudentService
    calls:
      - [ setEntityManager, [@doctrine.orm.entity_manager]]

  domain.subjects:
    class: WebDiario\CoreBundle\Services\Subjects\SubjectsService
    calls:
      - [ setEntityManager, [@doctrine.orm.entity_manager]]
      - [ setAuthenticationService, [@domain.authentication]]

  domain.professors:
      class: WebDiario\CoreBundle\Services\professors\ProfessorService
      calls:
        - [ setEntityManager, [@doctrine.orm.entity_manager]]
        - [ setAuthenticationService, [@domain.authentication]]