services:
     domain.authentication:
        class: WebDiario\CoreBundle\Services\Authentication\AuthenticationService
        calls:
          - [ setEntityManager, [@doctrine.orm.entity_manager]]
          - [ setContainer, [@service_container]]
