services:

    ## Listeners
    kernel.listner.kernel_exception:
      class: WebDiario\ApiBundle\Listener\ExceptionListener
      tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ## Controllers
    api.controller.login:
      class: WebDiario\ApiBundle\Controller\LoginController
      calls:
        - [setAuthenticationService, [@domain.authentication]]

    api.controller.students:
      class: WebDiario\ApiBundle\Controller\StudentsController
      calls:
        - [setAuthenticationService, [@domain.authentication]]
        - [setStudentService, [@domain.students]]

    api.controller.professors:
      class: WebDiario\ApiBundle\Controller\ProfessorsController
      calls:
        - [setAuthenticationService, [@domain.authentication]]
        - [setSubjectsService, [@domain.subjects]]
        - [setProfessorService, [@domain.professors]]