#Authentication Resource
api_login:
    path:     /login
    defaults: { _controller: api.controller.login:loginAction }
    methods: [POST]

api_logout:
    path:     /logout
    defaults: { _controller: api.controller.login:logoutAction }
    methods: [GET]