#Authentication Resource
api_login:
    path:     /login
    defaults: { _controller: api.controller.login:loginAction }
    methods: [POST]

api_logout:
    path:     /logout
    defaults: { _controller: api.controller.login:logoutAction }
    methods: [POST]

#Students Resource
api_student_list_all:
    path:     /alunos
    defaults: { _controller: api.controller.list.students:listAllStudents }
    methods: [GET]