#Authentication Resource
api_login:
    path:     /login
    defaults: { _controller: api.controller.login:loginAction }
    methods: [POST]

api_logout:
    path:     /logout
    defaults: { _controller: api.controller.login:logoutAction }
    methods: [POST]

#Students Resource
api_student_list_all:
    path:     /students/{id}
    defaults: { _controller: api.controller.students:listAllStudents }
    methods: [GET]

api_student_list_subjects:
    path:     /students/subjects/{id}
    defaults: { _controller: api.controller.students:listSubjectsByStudent}
    methods: [GET]

#Professors Resource
api_professor_list_subjects:
    path:     /professor/subjects/{id}
    defaults: { _controller: api.controller.professors:subjectList}
    methods: [GET]

api_professor_listall:
    path:     /professors/{id}
    defaults: { _controller: api.controller.professors:listProfessors}
    methods: [GET]

#Fouls
api_fouls:
    path:     /students/fouls
    defaults: { _controller: api.controller.students:createFouls}
    methods: [POST]

api_fouls_list:
    path:     /students/fouls/{id}
    defaults: { _controller: api.controller.students:listFouls}
    methods: [GET]