#Authentication Resource
api_login:
    path:     /login
    defaults: { _controller: api.controller.login:loginAction }
    methods: [POST]

api_logout:
    path:     /logout
    defaults: { _controller: api.controller.login:logoutAction }
    methods: [POST]

#Students Resource
api_student_list_all:
    path:     /alunos
    defaults: { _controller: api.controller.students:listAllStudents }
    methods: [GET]

#Professors Resource
api_professor_list_subjects:
    path:     /professor/subjects/{id}
    defaults: { _controller: api.controller.professors:subjectList}
    methods: [GET]